/**
 * 千手-淘淘英语学习 - 词库数据
 * 数据来源：第一天.pdf、第二天.pdf、第三天.pdf
 * 词条顺序与PDF原文保持一致
 * 总计：第一天76条、第二天72条、第三天68条，共216条
 */
var WORD_DATA = {
  "version": "1.0",
  "generatedAt": "2026-09-25",
  "source": "人教版高中英语词表（PDF扫描件）",
  "sets": [
    {
      "id": "day1",
      "name": "第一天",
      "source": "第一天.pdf",
      "description": "Unit 3 词汇及短语（含专有名词）",
      "words": [
        {"lemma": "buffet", "pron": "/'bʌfɪt/", "pos": "vt.", "meanings": "连续猛击；打来打去"},
        {"lemma": "buffet", "pron": "/'buːfeɪ; 'bʌfeɪ/", "pos": "n.", "meanings": "自助餐"},
        {"lemma": "cloth", "pron": "/klɒθ/", "pos": "n.", "meanings": "（一块）布；织物；布料"},
        {"lemma": "edge", "pron": "/edʒ/", "pos": "n.", "meanings": "边；边缘；边线；刀刃"},
        {"lemma": "edge", "pron": "/edʒ/", "pos": "vt. & vi.", "meanings": "（使）徐徐移动；给……加边"},
        {"lemma": "valley", "pron": "/'væli/", "pos": "n.", "meanings": "谷；山谷；溪谷"},
        {"lemma": "vast", "pron": "/vɑːst/", "pos": "adj.", "meanings": "辽阔的；巨大的；庞大的"},
        {"lemma": "melt", "pron": "/melt/", "pos": "vi. & vt.", "meanings": "（使）融化；熔化；软化"},
        {"lemma": "glacier", "pron": "/'ɡlæsiə(r)/", "pos": "n.", "meanings": "冰川"},
        {"lemma": "reindeer", "pron": "/'reɪndɪə(r)/", "pos": "n.", "meanings": "驯鹿"},
        {"lemma": "territory", "pron": "/'terətri/", "pos": "n.", "meanings": "领土；版图；领域；地盘"},
        {"lemma": "ban", "pron": "/bæn/", "pos": "vt.", "meanings": "明令禁止；取缔"},
        {"lemma": "ban", "pron": "/bæn/", "pos": "n.", "meanings": "禁令"},
        {"lemma": "boundary", "pron": "/'baʊndri/", "pos": "n.", "meanings": "边界；界限；分界线"},
        {"lemma": "cottage", "pron": "/'kɒtɪdʒ/", "pos": "n.", "meanings": "小屋；（尤指）村舍；小别墅"},
        {"lemma": "visible", "pron": "/'vɪzəbl/", "pos": "adj.", "meanings": "看得见的；可见的"},
        {"lemma": "on the move", "pron": "", "pos": "短语", "meanings": "在行进中；在移动中"},
        {"lemma": "accompany", "pron": "/əˈkʌmpəni/", "pos": "vt.", "meanings": "陪同；陪伴；伴随；（尤指用钢琴）为……伴奏"},
        {"lemma": "adopt", "pron": "/ə'dɒpt/", "pos": "vt. & vi.", "meanings": "采用；采取；采纳；领养"},
        {"lemma": "sour", "pron": "/'saʊə(r)/", "pos": "adj.", "meanings": "酸的；有酸味的"},
        {"lemma": "set out", "pron": "", "pos": "短语", "meanings": "出发；启程；（怀着目标）开始工作"},
        {"lemma": "bless", "pron": "/bles/", "pos": "vt.", "meanings": "祝福"},
        {"lemma": "live off", "pron": "", "pos": "短语", "meanings": "依靠……生活；以……为生"},
        {"lemma": "prohibition", "pron": "/ˌprəʊɪˈbɪʃn/", "pos": "n.", "meanings": "禁止；阻止；禁令"},
        {"lemma": "prohibit", "pron": "/prəˈhɪbɪt/", "pos": "vt.", "meanings": "（尤指以法令）禁止；阻止"},
        {"lemma": "journalist", "pron": "/ˈdʒɜːnəlɪst/", "pos": "n.", "meanings": "新闻记者；新闻工作者"},
        {"lemma": "sneeze", "pron": "/sniːz/", "pos": "vi.", "meanings": "打喷嚏"},
        {"lemma": "sneeze", "pron": "/sniːz/", "pos": "n.", "meanings": "喷嚏；喷嚏声"},
        {"lemma": "teapot", "pron": "/'tiːpɒt/", "pos": "n.", "meanings": "茶壶"},
        {"lemma": "label", "pron": "/'leɪbl/", "pos": "vt.", "meanings": "用标签标明；贴标签"},
        {"lemma": "label", "pron": "/'leɪbl/", "pos": "n.", "meanings": "标签；标记"},
        {"lemma": "cream", "pron": "/kriːm/", "pos": "n.", "meanings": "奶油；乳脂；护肤霜"},
        {"lemma": "stretch", "pron": "/stretʃ/", "pos": "vi. & vt.", "meanings": "延伸，延续；伸展，舒展"},
        {"lemma": "rewarding", "pron": "/rɪˈwɔːdɪŋ/", "pos": "adj.", "meanings": "值得做的；有益的"},
        {"lemma": "bush", "pron": "/bʊʃ/", "pos": "n.", "meanings": "灌木"},
        {"lemma": "lung", "pron": "/lʌŋ/", "pos": "n.", "meanings": "肺"},
        {"lemma": "cycle", "pron": "/saɪkl/", "pos": "n. & vi.", "meanings": "自行车；摩托车；循环；骑自行车"},
        {"lemma": "corridor", "pron": "/ˈkɒrɪdɔː(r)/", "pos": "n.", "meanings": "狭长地带；走廊；过道；通道"},
        {"lemma": "pedal", "pron": "/ˈpedl/", "pos": "n. & vt. & vi.", "meanings": "（自行车等的）脚镫子；踏板；骑自行车；踩踏板"},
        {"lemma": "fountain", "pron": "/ˈfaʊntən/", "pos": "n.", "meanings": "喷泉；人工喷泉；喷水池"},
        {"lemma": "route", "pron": "/ruːt/", "pos": "n.", "meanings": "路线；路途；途径"},
        {"lemma": "ahead", "pron": "/əˈhed/", "pos": "adv.", "meanings": "向前；在前面；提前"},
        {"lemma": "theme", "pron": "/θiːm/", "pos": "adj. & n.", "meanings": "有特定主题的；主题；主题思想"},
        {"lemma": "theme park", "pron": "", "pos": "短语", "meanings": "主题公园；主题乐园"},
        {"lemma": "roller coaster", "pron": "/ˈrəʊlə kəʊstə(r)/", "pos": "n.", "meanings": "过山车"},
        {"lemma": "incredible", "pron": "/ɪnˈkredəbl/", "pos": "adj.", "meanings": "极好的；极大的；难以置信的"},
        {"lemma": "appeal", "pron": "/əˈpiːl/", "pos": "vi. & n.", "meanings": "有吸引力；呼吁；恳求；上诉；吸引力；请求"},
        {"lemma": "appeal to", "pron": "", "pos": "短语", "meanings": "有吸引力；有感染力；呼吁；上诉；打动"},
        {"lemma": "pirate", "pron": "/'paɪrət/", "pos": "n. & vt.", "meanings": "海盗；盗版者；盗印；窃用"},
        {"lemma": "adorable", "pron": "/ə'dɔ:rəbl/", "pos": "adj.", "meanings": "可爱的；讨人喜爱的"},
        {"lemma": "wander", "pron": "/'wɒndə(r)/", "pos": "n. & vi. & vt.", "meanings": "游荡；闲逛；流浪；漫游；走失；离散；走神"},
        {"lemma": "amusement", "pron": "/ə'mju:zmənt/", "pos": "n.", "meanings": "娱乐（活动）；愉悦"},
        {"lemma": "amuse", "pron": "/ə'mju:z/", "pos": "vt.", "meanings": "（提供）消遣；（使）娱乐"},
        {"lemma": "enormous", "pron": "/ɪnɔ:məs/", "pos": "adj.", "meanings": "巨大的；极大的"},
        {"lemma": "swing", "pron": "/swɪŋ/", "pos": "vt. & vi.", "meanings": "( swung, swung )（使）摆动；摇摆；转弯；（使）突然转向"},
        {"lemma": "iron", "pron": "/'aɪən/", "pos": "n. & vt. & vi.", "meanings": "铁；铁器；铸铁；熨斗；（用熨斗）熨；烫平"},
        {"lemma": "fashion", "pron": "/'fæʃn/", "pos": "n.", "meanings": "时尚；时兴；流行款式"},
        {"lemma": "rare", "pron": "/reə(r)/", "pos": "adj.", "meanings": "稀少的；珍贵的；（肉）半熟的"},
        {"lemma": "steam", "pron": "/sti:m/", "pos": "n. & vi.", "meanings": "蒸汽；水蒸气；蒸汽动力；蒸发；散发蒸汽；冒水汽"},
        {"lemma": "superb", "pron": "/su:'pɜ:b/", "pos": "adj.", "meanings": "极佳的；卓越的"},
        {"lemma": "aquarium", "pron": "/ə'kweəriəm/", "pos": "n.", "meanings": "( pl. aquariums or aquaria ) 水族馆；水族玻璃槽；养鱼缸"},
        {"lemma": "up to", "pron": "", "pos": "短语", "meanings": "达到（某数量、程度等）；直到；不多于；（体力或智力上）能胜任"},
        {"lemma": "polar", "pron": "/'pəʊlə(r)/", "pos": "adj.", "meanings": "(近)极地的；南极(或北极)的；磁极的"},
        {"lemma": "upside down", "pron": "", "pos": "短语", "meanings": "颠倒；倒转；翻转"},
        {"lemma": "splendid", "pron": "/'splendɪd/", "pos": "adj.", "meanings": "壮丽的；雄伟的；极佳的；非常好的"},
        {"lemma": "display", "pron": "/dɪ'spleɪ/", "pos": "n. & vt.", "meanings": "展览；陈列；展览品；显示；陈列"},
        {"lemma": "appetite", "pron": "/'æpɪtaɪt/", "pos": "n.", "meanings": "食欲；胃口；强烈欲望"},
        {"lemma": "entertainment", "pron": "/ˌentə'teɪnmənt/", "pos": "n.", "meanings": "娱乐；招待；娱乐活动；文娱节目"},
        {"lemma": "column", "pron": "/'kɒləm/", "pos": "n.", "meanings": "(书、报纸印刷页上的)栏；专栏；柱(形物)"},
        {"lemma": "Sami", "pron": "/'sɑ:mi/", "pos": "n.", "meanings": "萨米人(居住在斯堪的纳维亚北部的拉普人)"},
        {"lemma": "Sarek National Park", "pron": "", "pos": "专有名词", "meanings": "萨勒克国家公园"},
        {"lemma": "Sweden", "pron": "/'swi:dn/", "pos": "n.", "meanings": "瑞典(国家名)"},
        {"lemma": "the Arctic Circle", "pron": "/'ɑ:ktɪk/", "pos": "专有名词", "meanings": "北极圈"},
        {"lemma": "Rapa River", "pron": "/'rɑ:pɑ:/", "pos": "专有名词", "meanings": "拉帕河"},
        {"lemma": "Siberian", "pron": "/saɪ'bɪərɪən/", "pos": "adj. & n.", "meanings": "西伯利亚(人)的；西伯利亚人"},
        {"lemma": "Dollywood", "pron": "/'dɒli,wud/", "pos": "n.", "meanings": "多莉山主题公园"}
      ]
    },
    {
      "id": "day2",
      "name": "第二天",
      "source": "第二天.pdf",
      "description": "Unit 4 词汇及短语（肢体语言与非言语交际）",
      "words": [
        {"lemma": "interaction", "pron": "/ˌɪntərˈækʃn/", "pos": "n.", "meanings": "交流；相互影响"},
        {"lemma": "vary", "pron": "/ˈveəri/", "pos": "vi.", "meanings": "（根据情况）变化；改变"},
        {"lemma": "appropriate", "pron": "/əˈprəʊpriət/", "pos": "adj.", "meanings": "合适的；恰当的"},
        {"lemma": "by contrast", "pron": "", "pos": "短语", "meanings": "相比之下"},
        {"lemma": "approve", "pron": "/əˈpruːv/", "pos": "vi. & vt.", "meanings": "赞成；同意；批准；通过"},
        {"lemma": "demonstrate", "pron": "/ˈdemənstreɪt/", "pos": "vt.", "meanings": "表现；表达；说明；证明"},
        {"lemma": "gesture", "pron": "/ˈdʒestʃə(r)/", "pos": "n.", "meanings": "手势；姿势；姿态"},
        {"lemma": "witness", "pron": "/ˈwɪtnəs/", "pos": "vt. & n.", "meanings": "当场看到；目击；见证；目击者；证人"},
        {"lemma": "employ", "pron": "/ɪmˈplɔɪ/", "pos": "vt.", "meanings": "使用；应用；雇用"},
        {"lemma": "identical", "pron": "/aɪˈdentɪkl/", "pos": "adj.", "meanings": "相同的"},
        {"lemma": "interpret", "pron": "/ɪnˈtɜːprɪt/", "pos": "vt. & vi.", "meanings": "把……理解（解释）为；口译"},
        {"lemma": "differ", "pron": "/ˈdɪfə(r)/", "pos": "vi.", "meanings": "相异；不同于"},
        {"lemma": "by comparison", "pron": "", "pos": "短语", "meanings": "（与……）相比较"},
        {"lemma": "cheek", "pron": "/tʃiːk/", "pos": "n.", "meanings": "面颊；脸颊"},
        {"lemma": "favour", "pron": "/ˈfeɪvə(r)/", "pos": "vt. & n.", "meanings": "较喜欢；选择；有利于；帮助；恩惠；赞同"},
        {"lemma": "bow", "pron": "/baʊ/ /bəʊ/", "pos": "vi. & n.", "meanings": "鞠躬；点头；低（头）；弓；蝴蝶结"},
        {"lemma": "waist", "pron": "/weɪst/", "pos": "n.", "meanings": "腰；腰部"},
        {"lemma": "make inferences", "pron": "", "pos": "短语", "meanings": "推理；推断"},
        {"lemma": "break down", "pron": "", "pos": "短语", "meanings": "消除；分解；打破"},
        {"lemma": "barrier", "pron": "/ˈbæriə(r)/", "pos": "n.", "meanings": "隔阂；障碍"},
        {"lemma": "fake", "pron": "/feɪk/", "pos": "adj.", "meanings": "假装的；假的；冒充的"},
        {"lemma": "anger", "pron": "/ˈæŋɡə(r)/", "pos": "n. & vt.", "meanings": "愤怒；怒气；使生气；激怒"},
        {"lemma": "reliable", "pron": "/rɪˈlaɪəbl/", "pos": "adj.", "meanings": "可靠的；可信赖的"},
        {"lemma": "incident", "pron": "/ˈɪnsɪdənt/", "pos": "n.", "meanings": "发生的事情；严重事件；冲突"},
        {"lemma": "trial", "pron": "/ˈtraɪəl/", "pos": "n. & v.", "meanings": "审讯；审判；试验；试用"},
        {"lemma": "slight", "pron": "/slaɪt/", "pos": "adj.", "meanings": "轻微的；略微的；细小的"},
        {"lemma": "slightly", "pron": "/ˈslaɪtli/", "pos": "adv.", "meanings": "略微；稍微"},
        {"lemma": "twin", "pron": "/twɪn/", "pos": "adj. & n.", "meanings": "双胞胎之一的；孪生之一；孪生之一；双胞胎之一"},
        {"lemma": "nonverbal", "pron": "/ˌnɒnˈvɜːbl/", "pos": "adj.", "meanings": "不涉及言语的；非言语的"},
        {"lemma": "assessment", "pron": "/əˈsesmənt/", "pos": "n.", "meanings": "评价；评定"},
        {"lemma": "assess", "pron": "/əˈses/", "pos": "vt.", "meanings": "评估；评价"},
        {"lemma": "internal", "pron": "/ɪnˈtɜːnl/", "pos": "adj.", "meanings": "内部的；里面的"},
        {"lemma": "straighten up", "pron": "", "pos": "短语", "meanings": "直起来；整理；收拾整齐"},
        {"lemma": "slump", "pron": "/slʌmp/", "pos": "vi.", "meanings": "垂头弯腰地走（或坐等）"},
        {"lemma": "pose", "pron": "/pəʊz/", "pos": "n. & vi. & vt.", "meanings": "故作姿态；（为画像、拍照等摆的）姿势；摆好姿势；造成（威胁、问题等）"},
        {"lemma": "bend", "pron": "/bend/", "pos": "vt. & vi.", "meanings": "（bent, bent）（使）弯曲；倾斜；偏向"},
        {"lemma": "reveal", "pron": "/rɪˈviːl/", "pos": "vt.", "meanings": "揭示；显示；露出"},
        {"lemma": "clarify", "pron": "/ˈklærəfaɪ/", "pos": "vt.", "meanings": "使更清晰易懂；阐明；澄清"},
        {"lemma": "in other words", "pron": "", "pos": "短语", "meanings": "换句话说；也就是说"},
        {"lemma": "educator", "pron": "/ˈedʒukeɪtə(r)/", "pos": "n.", "meanings": "教师；教育工作者；教育家"},
        {"lemma": "tick", "pron": "/tɪk/", "pos": "vt. & vi. & n.", "meanings": "给（试卷、问题等）打钩号；（钟表）发出嘀嗒声；钩号"},
        {"lemma": "tendency", "pron": "/ˈtendənsi/", "pos": "n.", "meanings": "趋势；倾向"},
        {"lemma": "lower", "pron": "/ˈləʊə(r)/", "pos": "vt. & adj.", "meanings": "把……放低；降低；减少；下面的；下方的；较小的"},
        {"lemma": "imply", "pron": "/ɪmˈplaɪ/", "pos": "vt.", "meanings": "意味着；暗示"},
        {"lemma": "barely", "pron": "/ˈbeəli/", "pos": "adv.", "meanings": "几乎不；勉强才能；刚刚"},
        {"lemma": "chin", "pron": "/tʃɪn/", "pos": "n.", "meanings": "下巴"},
        {"lemma": "occupy", "pron": "/ˈɒkjupaɪ/", "pos": "vt.", "meanings": "占据；占用"},
        {"lemma": "stare", "pron": "/steə(r)/", "pos": "vi. & n.", "meanings": "盯着看；凝视"},
        {"lemma": "ceiling", "pron": "/ˈsiːlɪŋ/", "pos": "n.", "meanings": "天花板；上限"},
        {"lemma": "distract", "pron": "/dɪˈstrækt/", "pos": "vt.", "meanings": "分散（注意力）；使分心"},
        {"lemma": "perceive", "pron": "/pəˈsiːv/", "pos": "vt.", "meanings": "察觉；看待；理解"},
        {"lemma": "distinguish", "pron": "/dɪˈstɪŋɡwɪʃ/", "pos": "vi. & vt.", "meanings": "区分；辨别"},
        {"lemma": "anxiety", "pron": "/æŋˈzaɪəti/", "pos": "n.", "meanings": "焦虑；担心；害怕"},
        {"lemma": "chest", "pron": "/tʃest/", "pos": "n.", "meanings": "胸部；胸膛"},
        {"lemma": "embarrassed", "pron": "/ɪmˈbærəst/", "pos": "adj.", "meanings": "难堪的；尴尬的"},
        {"lemma": "ashamed", "pron": "/əˈʃeɪmd/", "pos": "adj.", "meanings": "羞愧；惭愧"},
        {"lemma": "merely", "pron": "/ˈmɪəli/", "pos": "adv.", "meanings": "只是；仅仅；只不过"},
        {"lemma": "call on", "pron": "", "pos": "短语", "meanings": "（短暂地）访问；要求（某人讲话等）；正式邀请"},
        {"lemma": "bother", "pron": "/ˈbɒðə(r)/", "pos": "vi. & vt. & n.", "meanings": "费心；麻烦；因……操心；麻烦；不便"},
        {"lemma": "weep", "pron": "/wiːp/", "pos": "vi. & vt.", "meanings": "（wept, wept）哭泣；流泪"},
        {"lemma": "at work", "pron": "", "pos": "短语", "meanings": "有某种影响；在工作"},
        {"lemma": "conflict", "pron": "/ˈkɒnflɪkt/ /kənˈflɪkt/", "pos": "n. & vi.", "meanings": "矛盾；冲突；冲突；抵触"},
        {"lemma": "inquire", "pron": "/ɪnˈkwaɪə(r)/", "pos": "vi. & vt.", "meanings": "（= enquire）询问；打听"},
        {"lemma": "ultimately", "pron": "/ˈʌltɪmətli/", "pos": "adv.", "meanings": "最终；最后"},
        {"lemma": "adjust", "pron": "/əˈdʒʌst/", "pos": "vt. & vi.", "meanings": "调整；调节；适应；（使）习惯"},
        {"lemma": "intervene", "pron": "/ˌɪntəˈviːn/", "pos": "vi.", "meanings": "干预；介入"},
        {"lemma": "react", "pron": "/rɪˈækt/", "pos": "vi.", "meanings": "（对……）起反应；回应；（对食物等）有不良反应"},
        {"lemma": "component", "pron": "/kəmˈpəʊnənt/", "pos": "n.", "meanings": "组成部分；零件"},
        {"lemma": "tone", "pron": "/təʊn/", "pos": "n.", "meanings": "语气；腔调；口吻"},
        {"lemma": "Brazil", "pron": "/brəˈzɪl/", "pos": "n.", "meanings": "巴西（国家名）"},
        {"lemma": "Bulgaria", "pron": "/bʌlˈɡeəriə/", "pos": "n.", "meanings": "保加利亚（国家名）"},
        {"lemma": "Albania", "pron": "/ælˈbeɪniə/", "pos": "n.", "meanings": "阿尔巴尼亚（国家名）"}
      ]
    },
    {
      "id": "day3",
      "name": "第三天",
      "source": "第三天.pdf",
      "description": "Unit 5 词汇及短语（农业科技与杂交水稻）",
      "words": [
        {"lemma": "hybrid", "pron": "/'haɪbrɪd/", "pos": "n.", "meanings": "杂交植（动）物；合成物；混合动力车"},
        {"lemma": "devote", "pron": "/dɪ'vəʊt/", "pos": "vt.", "meanings": "把……献（给）；把……专用于；专心于（devote...to 把……用于；献身；致力；专心）"},
        {"lemma": "shortage", "pron": "/'ʃɔːtɪdʒ/", "pos": "n.", "meanings": "不足；缺少；短缺"},
        {"lemma": "tackle", "pron": "/'tækl/", "pos": "vt.", "meanings": "解决（难题）；应付（局面）；处理"},
        {"lemma": "crisis", "pron": "/'kraɪsɪs/", "pos": "n.", "meanings": "( pl. crises ) 危机；危急关头"},
        {"lemma": "boost", "pron": "/buːst/", "pos": "vt. & n.", "meanings": "使增长；使兴旺；增长；提高；激励"},
        {"lemma": "yield", "pron": "/jiːld/", "pos": "n. & vt. & vi.", "meanings": "产量；产出；出产（作物）；产生（收益、效益等）；屈服；让步"},
        {"lemma": "convince", "pron": "/kən'vɪns/", "pos": "vt.", "meanings": "使相信；使确信；说服"},
        {"lemma": "characteristic", "pron": "/ˌkærəktə'rɪstɪk/", "pos": "n. & adj.", "meanings": "特征；特点；品质；典型的；独特的"},
        {"lemma": "attain", "pron": "/əˈteɪn/", "pos": "vt.", "meanings": "（通常经过努力）获得；得到"},
        {"lemma": "conventional", "pron": "/kənˈvenʃənl/", "pos": "adj.", "meanings": "传统的；习惯的"},
        {"lemma": "pollinate", "pron": "/ˈpɒləneɪt/", "pos": "vt.", "meanings": "授粉；传粉"},
        {"lemma": "assumption", "pron": "/əˈsʌmpʃn/", "pos": "n.", "meanings": "假定；设定；（责任的）承担；（权力的）获得"},
        {"lemma": "intense", "pron": "/ɪnˈtens/", "pos": "adj.", "meanings": "热切的；十分强烈的；激烈的"},
        {"lemma": "overcome", "pron": "/ˌəʊvəˈkʌm/", "pos": "vt.", "meanings": "（overcame, overcome）克服；解决；战胜"},
        {"lemma": "expand", "pron": "/ɪkˈspænd/", "pos": "vt. & vi.", "meanings": "扩大；增加；扩展；发展（业务）"},
        {"lemma": "output", "pron": "/ˈaʊtpʊt/", "pos": "n. & vt.", "meanings": "产量；输出；输出量；（output, output）输出"},
        {"lemma": "estimate", "pron": "/ˈestɪmət/", "pos": "vt. & n.", "meanings": "估计；估价；估算；估计；估算"},
        {"lemma": "domestic", "pron": "/dəˈmestɪk/", "pos": "adj.", "meanings": "本国的；国内的；家用的；家庭的"},
        {"lemma": "consumption", "pron": "/kənˈsʌmpʃn/", "pos": "n.", "meanings": "消耗；消耗量；消费"},
        {"lemma": "comprise", "pron": "/kəmˈpraɪz/", "pos": "vt.", "meanings": "包括；包含；由……组成"},
        {"lemma": "be comprised of", "pron": "", "pos": "短语", "meanings": "包括；包含；由……组成（或构成）"},
        {"lemma": "generate", "pron": "/ˈdʒenəreɪt/", "pos": "vt.", "meanings": "产生；引起"},
        {"lemma": "strain", "pron": "/streɪn/", "pos": "n.", "meanings": "（动、植物的）系；品种；拉伤；压力"},
        {"lemma": "leisure", "pron": "/ˈleʒə(r)/", "pos": "n.", "meanings": "闲暇；休闲；空闲"},
        {"lemma": "deep down", "pron": "", "pos": "短语", "meanings": "在内心深处；本质上；实际上"},
        {"lemma": "soil", "pron": "/sɔɪl/", "pos": "n.", "meanings": "泥土；土壤；国土；领土"},
        {"lemma": "celebrity", "pron": "/səˈlebrəti/", "pos": "n.", "meanings": "名望；名誉；名人；名流"},
        {"lemma": "envision", "pron": "/ɪnˈvɪʒn/", "pos": "vt.", "meanings": "展望；想象"},
        {"lemma": "sorghum", "pron": "/ˈsɔːɡəm/", "pos": "n.", "meanings": "高粱；高粱米"},
        {"lemma": "broom", "pron": "/bruːm/", "pos": "n.", "meanings": "扫把；扫帚；金雀花"},
        {"lemma": "grain", "pron": "/ɡreɪn/", "pos": "n.", "meanings": "谷物；谷粒；颗粒"},
        {"lemma": "vision", "pron": "/ˈvɪʒn/", "pos": "n.", "meanings": "想象；视力；视野；影像"},
        {"lemma": "reality", "pron": "/riˈæləti/", "pos": "n.", "meanings": "现实；实际情况；事实"},
        {"lemma": "salty", "pron": "/ˈsɔːlti/", "pos": "adj.", "meanings": "含盐的；咸的"},
        {"lemma": "urban", "pron": "/ˈɜːbən/", "pos": "adj.", "meanings": "城市的；都市的；城镇的"},
        {"lemma": "bomb", "pron": "/bɒm/", "pos": "n. & vt.", "meanings": "炸弹；轰炸；对……投炸弹"},
        {"lemma": "tunnel", "pron": "/ˈtʌnl/", "pos": "n.", "meanings": "地下通道；地道；隧道"},
        {"lemma": "extension", "pron": "/ɪkˈstenʃn/", "pos": "n.", "meanings": "扩建部分；扩大；电话分机"},
        {"lemma": "chemical", "pron": "/'kemɪkl/", "pos": "adj. & n.", "meanings": "与化学有关的；化学的；化学制品；化学品"},
        {"lemma": "wheat", "pron": "/wiːt/", "pos": "n.", "meanings": "小麦；小麦籽"},
        {"lemma": "flavour", "pron": "/'fleɪvə/", "pos": "n.", "meanings": "味道；特点；特色"},
        {"lemma": "fertiliser", "pron": "/'fɜːtəlaɪzə(r)/", "pos": "n.", "meanings": "肥料"},
        {"lemma": "nutritional", "pron": "/nju'trɪʃənl/", "pos": "adj.", "meanings": "营养（物）的"},
        {"lemma": "nutritious", "pron": "/nju'trɪʃəs/", "pos": "adj.", "meanings": "有营养的；营养丰富的"},
        {"lemma": "nutrition", "pron": "/nju'trɪʃn/", "pos": "n.", "meanings": "营养；滋养"},
        {"lemma": "alleviate", "pron": "/ə'liːvieɪt/", "pos": "vt.", "meanings": "减轻；缓解"},
        {"lemma": "poverty", "pron": "/'pɒvəti/", "pos": "n.", "meanings": "贫穷；贫困"},
        {"lemma": "organic", "pron": "/ɔː'ɡænɪk/", "pos": "adj.", "meanings": "有机的；不使用化肥的；有机物的"},
        {"lemma": "pesticide", "pron": "/'pestɪsaɪd/", "pos": "n.", "meanings": "杀虫剂；除害药物"},
        {"lemma": "widespread", "pron": "/'waɪdspred/", "pos": "adj.", "meanings": "分布广的；普遍的；广泛的"},
        {"lemma": "bacterium", "pron": "/bæk'tɪəriəm/", "pos": "n.", "meanings": "( pl. -ria ) 细菌"},
        {"lemma": "in turn", "pron": "", "pos": "短语", "meanings": "相应地；转而；依次；轮流"},
        {"lemma": "digest", "pron": "/daɪ'dʒest/ /'daɪdʒest/", "pos": "vt. & vi. & n.", "meanings": "消化；领会；领悟；摘要；文摘"},
        {"lemma": "essential", "pron": "/ɪ'senʃl/", "pos": "adj.", "meanings": "完全必要的；极其重要的"},
        {"lemma": "mineral", "pron": "/'mɪnərəl/", "pos": "n.", "meanings": "矿物；矿物质"},
        {"lemma": "alternative", "pron": "/ɔːl'tɜːnətɪv/", "pos": "n. & adj.", "meanings": "可供选择的事物；可供替代的；非传统的"},
        {"lemma": "grocery", "pron": "/ˈɡrəʊsəri/", "pos": "n.", "meanings": "食品杂货店；[pl.] 食品杂货"},
        {"lemma": "instance", "pron": "/ˈɪnstəns/", "pos": "n.", "meanings": "例子；实例；事例"},
        {"lemma": "for instance", "pron": "", "pos": "短语", "meanings": "例如；比如"},
        {"lemma": "batch", "pron": "/bætʃ/", "pos": "n. & vt.", "meanings": "一批；一组；分批处理"},
        {"lemma": "depth", "pron": "/depθ/", "pos": "n.", "meanings": "向下（或向里）的距离；深（度）"},
        {"lemma": "root", "pron": "/ruːt/", "pos": "n.", "meanings": "根；根茎；根部；根源"},
        {"lemma": "entirely", "pron": "/ɪnˈtaɪəli/", "pos": "adv.", "meanings": "全部地；完整地；完全地"},
        {"lemma": "aspect", "pron": "/ˈæspekt/", "pos": "n.", "meanings": "方面；层面"},
        {"lemma": "Vietnam", "pron": "/ˌvjetˈnæm/", "pos": "n.", "meanings": "越南（国家名）"},
        {"lemma": "LED", "pron": "", "pos": "abbr.", "meanings": "（light-emitting diode）发光二极管"},
        {"lemma": "DDT", "pron": "", "pos": "n.", "meanings": "滴滴涕（旧时尤用作农业杀虫剂）"}
      ]
    }
  ]
};
